### ISSUE TITLE
use localhost and override a few defaults in example playbook

### ISSUE THREAD

**Issue by LeoUfimtsev** [victorock/ansible-role-ansible-tower-setup#5]
Hello, 

Thank you very much for this role. Exactly what I was looking for.

I'm planning to write about it on the Red Hat developer blog (I'm a Red Hat employee). Would you be able to update the example and show how to override a few default values?
https://docs.ansible.com/ansible/2.5/user_guide/playbooks_reuse_roles.html 

Some people who are not experienced with ansible might struggle. 

I'd recommend to change the example host to 'localhost' as oppose to 'tower', as the usual use case is probably running the playbook on the tower machine.

**Comment by victorock** [comment]
Hello @LeoUfimtsev thanks for the heads up.
Feel free to send your PR. PRs are welcome, the most complete example of vars being consumed by this and the tower_config role: https://github.com/victorock/ansible-devops/tree/dev/applications/ansible-tower/group_vars/tower

This is what i am using to autobuild my Tower demo environment in GoogleCloud: https://github.com/victorock/ansible-devops/tree/dev/applications/ansible-tower

**Comment by victorock** [comment]
If you use localhost, it means you are installing locally. In my case, i am using a provisioned server in the cloud, with the proper tags and dynamic inventory. This allows me to download and deploy Tower in whatever remote server(s). Follow here the link of an example: https://github.com/victorock/ansible-devops/tree/dev/applications/ansible-tower

**Comment by victorock** [comment]
The variables in the role's default has the lowest precedence, so you can override from whatever you want: inventory, vars, playbook, etc... (Ref: https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable)
